### ISSUE TITLE
diffLines gets slow when text has many lines

### ISSUE THREAD

**Issue by jinjor** [avh4/elm-diff#8]
Hi @avh4 ,

I'm using this library in [elm-time-travel](https://github.com/jinjor/elm-time-travel) project, and found it very useful. Thank you for making this!

However, when the text has many lines, `diffLines` gets very slow. For instance, comparing [this string](https://github.com/jinjor/elm-time-travel/blob/master/test/BenchmarkDiff.elm#L27) 10 times took 25s. I expected this to be less than 1s (this number has no reason, just my feeling).

Is this performance hard to improve? I'm not familiar with diff algorithms, but if you know something about it, it would be very helpful for me to share your ideas. (I know there is "Patience algorithm" from the README, but don't know how hard to implement it)

Thanks.

**Comment by avh4** [comment]
Well, it's possible that the implementation here is incorrect.  I'm not completely sure I've implemented the algorithm correctly.

However, the algorithm when correct is `O(n*m)`, which is not great.  I'm not sure whether the Patience algorithm would perform significantly better (it probably wouldn't be _that_ much better).  What I've noticed is that most real-world diff programs achieve speed by giving up on finding a match after a certain number of lines have been checked.

To summarize, I think one of the following is the case, but I'm not sure which: 1) elm-diff implements the current algorithm incorrectly and is slow because of an incorrect implementation; 2) another algorithm (possible Patience) would be faster for realistic use-cases; 3) no "correct" algorithm will be fast enough, and we need to implement heuristics to know when to give up on finding the "best" solution to a diff and instead return something quickly.

For your case of elm-time-travel, I'm guessing you are starting with structured data, converting it to a string and then diffing the string?  Since the data has structure to begin with, you might try converting the data into some kind of generic tree and then diffing the tree -- doing something like that would probably be a lot faster than diffing the string representations.

**Comment by jinjor** [comment]
Thank you for your kind answer! This is very helpful.
It's also interesting for me to hear that some heuristics may be used in real-world diff.

>  For your case of elm-time-travel, I'm guessing you are starting with structured data, converting it to a string and then diffing the string?

Yeah, exactly. I chose the easy way to use existing library, but should have tried diffing the original structure. I'll try it when I have time!

(Maybe I should close this issue?)

**Comment by jinjor** [comment]
Yesterday I made [another diff library](https://github.com/jinjor/elm-diff) and it looks working faster. [The O(ND) algorithm](http://www.xmailserver.org/diff2.pdf) is great!
So I close this issue. Thanks anyway ;)

**Comment by avh4** [comment]
@jinjor should people now prefer your library?  or are there still situations where mine will be better?

**Comment by jinjor** [comment]
I compared their performance just now, using [this](https://github.com/jinjor/elm-diff/blob/master/test/Benchmarks.elm#L17-L29) test case.

Average time:

| test case | avh4/elm-diff | jinjor/elm-diff |
| :-- | :-- | :-- |
| exactly same | 1.9s | 0.0007s |
| add line to first | 2.0s | 0.0006s |
| add line to last | 2.0s | 0.0005s |
| drop first line | 2.3s | 0.0005s |
| remove line at middle | 2.0s | 0.0006s |
| add line at middle | 2.3s | 0.0006s |
| modify all | 2.1s | 1.1s |
| add all | 0.000007s | 0.4s |
| remove all | 0.000007s | 0.4s |

It seems they implement O(MN) and O(ND) correctly. I think most of the case people should use mine, because we usually compare between many lines and another many lines.
